import type { LearnStage } from './types'
import { emptyRows } from './boardSetup'

/**
 * 커리큘럼 설계 참고 (오리지널 문제 · 복제 아님):
 * - Graded Go Problems for Beginners (Kano) — 따냄·단수·기초 사활 단계
 * - Elementary Go Series: In the Beginning / Life and Death — 포석·눈 개념
 * - 한국 입문 교재 공통: 화점·3-4·활로·두 눈
 */

const e9 = emptyRows(9)

export const STAGES: LearnStage[] = [
  // ─── 기본 배우기 ─────────────────────────────────────────
  {
    id: 'basics-1',
    track: 'basics',
    order: 1,
    title: { ko: '1. 판과 교차점', en: '1. Board & points' },
    blurb: {
      ko: '바둑은 선이 아니라 교차점에 둡니다. 먼저 판의 기준점(화점)을 익히세요.',
      en: 'Stones go on intersections. Learn the star points first.',
    },
    refs: {
      ko: '참고: 입문 교재 공통 · Graded Go Problems Vol.1 도입',
      en: 'Ref: beginner intros · Graded Go Problems Vol.1 intro',
    },
    problems: [
      {
        id: 'b1-center',
        title: { ko: '천원(중앙) 두기', en: 'Play the center' },
        goalLabel: { ko: '목표: 판 정중앙에 두기', en: 'Goal: play the exact center' },
        goal: 'place',
        size: 9,
        toPlay: 1,
        setup: e9,
        solutions: [{ x: 4, y: 4 }],
        hint: { ko: '9×9에서 가운데 교차점(E5).', en: 'On 9×9 that is E5 (0-indexed 4,4).' },
        note: { ko: '중앙은 영향력이 넓지만, 실전에서는 귀·변이 더 효율적인 경우가 많습니다.', en: 'Center has influence; corners are often more efficient early.' },
      },
      {
        id: 'b1-hoshi',
        title: { ko: '화점 고르기', en: 'Pick a star point' },
        goalLabel: { ko: '목표: 9줄 화점 중 한 곳에 두기', en: 'Goal: play any 9×9 star point' },
        goal: 'place',
        size: 9,
        toPlay: 1,
        setup: e9,
        solutions: [
          { x: 2, y: 2 }, { x: 6, y: 2 }, { x: 4, y: 4 }, { x: 2, y: 6 }, { x: 6, y: 6 },
        ],
        hint: { ko: '화점은 두꺼운 점(·)으로 표시됩니다.', en: 'Star points are the marked hoshi dots.' },
      },
      {
        id: 'b1-corner34',
        title: { ko: '귀의 3-4', en: '3-4 in the corner' },
        goalLabel: { ko: '목표: 좌상귀 3-4에 두기', en: 'Goal: play 3-4 of the top-left corner' },
        goal: 'place',
        size: 9,
        toPlay: 1,
        setup: e9,
        solutions: [{ x: 2, y: 3 }, { x: 3, y: 2 }],
        hint: { ko: '귀에서 3줄·4줄이 만나는 점(두 곳 중 하나).', en: 'Either 3-4 orientation in that corner.' },
        note: { ko: '3-4는 유연한 포석의 기본. 《In the Beginning》에서도 강조합니다.', en: '3-4 is a flexible opening staple (In the Beginning).' },
      },
    ],
  },
  {
    id: 'basics-2',
    track: 'basics',
    order: 2,
    title: { ko: '2. 활로와 따냄', en: '2. Liberties & capture' },
    blurb: {
      ko: '돌의 상하좌우 빈 점이 활로입니다. 활로를 모두 막으면 따냅니다.',
      en: 'Orthogonally adjacent empty points are liberties. Fill them all to capture.',
    },
    refs: {
      ko: '참고: Graded Go Problems for Beginners Vol.1 — 따냄·단수',
      en: 'Ref: Graded Go Problems Vol.1 — capturing & atari',
    },
    problems: [
      {
        id: 'b2-cap-corner',
        title: { ko: '귀 근처 한 점 따내기', en: 'Capture near the corner' },
        goalLabel: { ko: '목표: 백 돌 따내기', en: 'Goal: capture the white stone' },
        goal: 'capture',
        size: 9,
        toPlay: 1,
        setup: [
          '.........',
          '.........',
          '.........',
          '.........',
          '.........',
          '.........',
          '.B.......',
          'BW.......',
          '.B.......',
        ],
        solutions: [{ x: 2, y: 7 }],
        hint: { ko: '백의 남은 활로(오른쪽)를 막으세요.', en: 'Fill White’s last liberty to the right.' },
      },
      {
        id: 'b2-atari',
        title: { ko: '단수 처리', en: 'Answer atari' },
        goalLabel: { ko: '목표: 단수인 백 따내기', en: 'Goal: capture the stone in atari' },
        goal: 'capture',
        size: 9,
        toPlay: 1,
        setup: [
          '.........',
          '.........',
          '..BBB....',
          '.BW.B....',
          '..BBB....',
          '.........',
          '.........',
          '.........',
          '.........',
        ],
        solutions: [{ x: 3, y: 3 }],
        hint: { ko: '활로가 하나뿐인 곳을 두세요.', en: 'Play on the single remaining liberty.' },
      },
      {
        id: 'b2-two',
        title: { ko: '두 점 한꺼번에', en: 'Capture two stones' },
        goalLabel: { ko: '목표: 백 두 점 따내기', en: 'Goal: capture both white stones' },
        goal: 'capture',
        size: 9,
        toPlay: 1,
        setup: [
          '.........',
          '.........',
          '.........',
          '..BBB....',
          '.BWWB....',
          '..B.B....',
          '...B.....',
          '.........',
          '.........',
        ],
        solutions: [{ x: 3, y: 5 }],
        hint: { ko: '연결 백 덩어리의 빈 칸을 메우세요.', en: 'Fill the shared liberty of the white chain.' },
      },
      {
        id: 'b2-edge',
        title: { ko: '변에서 잡기', en: 'Capture on the side' },
        goalLabel: { ko: '목표: 백 돌 따내기', en: 'Goal: capture White' },
        goal: 'capture',
        size: 9,
        toPlay: 1,
        setup: [
          '.........',
          '.........',
          '.........',
          '.........',
          'BBB......',
          'BWB......',
          'B.B......',
          '.........',
          '.........',
        ],
        solutions: [{ x: 1, y: 6 }],
        hint: { ko: '아래쪽 활로를 막으세요.', en: 'Block the liberty below.' },
      },
    ],
  },
  {
    id: 'basics-3',
    track: 'basics',
    order: 3,
    title: { ko: '3. 연결과 집 감각', en: '3. Connection & territory feel' },
    blurb: {
      ko: '같은 색이 붙으면 한 덩어리입니다. 집은 ‘둘러싼 빈 점’이고, 끝내기는 패스를 두 번 하면 끝납니다.',
      en: 'Connected stones share liberties. Territory is surrounded empty points; two passes end the game.',
    },
    refs: {
      ko: '참고: 입문 끝내기 · Graded Go Problems 기초 연결',
      en: 'Ref: intro endgame · Graded Go connection drills',
    },
    problems: [
      {
        id: 'b3-connect',
        title: { ko: '끊기지 않게 잇기', en: 'Connect safely' },
        goalLabel: { ko: '목표: 흑 두 점을 잇는 수', en: 'Goal: the move that connects Black' },
        goal: 'place',
        size: 9,
        toPlay: 1,
        setup: [
          '.........',
          '.........',
          '.........',
          '..B.B....',
          '...W.....',
          '.........',
          '.........',
          '.........',
          '.........',
        ],
        solutions: [{ x: 3, y: 3 }],
        hint: { ko: '두 흑 사이의 빈 칸.', en: 'The empty point between the two Blacks.' },
      },
      {
        id: 'b3-cut',
        title: { ko: '끊기', en: 'Cut' },
        goalLabel: { ko: '목표: 백 연결을 끊는 수', en: 'Goal: cut White’s connection' },
        goal: 'place',
        size: 9,
        toPlay: 1,
        setup: [
          '.........',
          '.........',
          '...B.....',
          '..W.W....',
          '...B.....',
          '.........',
          '.........',
          '.........',
          '.........',
        ],
        solutions: [{ x: 3, y: 3 }],
        hint: { ko: '백 사이에 끼워 두세요.', en: 'Play between the two Whites.' },
      },
      {
        id: 'b3-eye-spot',
        title: { ko: '눈 자리 감각', en: 'Eye-space sense' },
        goalLabel: { ko: '목표: 흑이 눈을 키우는 급소', en: 'Goal: key point to expand Black’s eye' },
        goal: 'live',
        size: 9,
        toPlay: 1,
        setup: [
          '.........',
          '.........',
          '..BBB....',
          '..B.B....',
          '..BBB....',
          '.........',
          '.........',
          '.........',
          '.........',
        ],
        solutions: [{ x: 3, y: 3 }],
        hint: { ko: '가운데 빈 칸이 눈의 중심입니다.', en: 'The hollow center is the eye point.' },
        note: { ko: '한 눈만으로는 부족하고, 두 눈이 있어야 삽니다(다음 트랙).', en: 'One eye is not enough — two eyes live (next track).' },
      },
    ],
  },

  // ─── 포석 배우기 ─────────────────────────────────────────
  {
    id: 'fuseki-1',
    track: 'fuseki',
    order: 1,
    title: { ko: '1. 귀·화점 우선', en: '1. Corners & hoshi first' },
    blurb: {
      ko: '포석은 귀→변→중앙. 화점은 영향력이 크고, 3-4는 실리를 노리기 쉽습니다.',
      en: 'Opening order: corner → side → center. Hoshi for influence; 3-4 for territory.',
    },
    refs: {
      ko: '참고: Elementary Go Series — In the Beginning (Ishigure)',
      en: 'Ref: Elementary Go Series — In the Beginning',
    },
    problems: [
      {
        id: 'f1-first-corner',
        title: { ko: '첫 수는 귀', en: 'First move in a corner' },
        goalLabel: { ko: '목표: 우상귀 화점(6,2)에 두기', en: 'Goal: play hoshi of top-right (6,2)' },
        goal: 'place',
        size: 9,
        toPlay: 1,
        setup: e9,
        solutions: [{ x: 6, y: 2 }],
        hint: { ko: '오른쪽 위 화점.', en: 'Top-right star point.' },
      },
      {
        id: 'f1-answer-approach',
        title: { ko: '걸침에 받기', en: 'Answer an approach' },
        goalLabel: { ko: '목표: 흑 화점에 대한 백의 적절한 응수(옆 3-4)', en: 'Goal: proper reply beside Black hoshi' },
        goal: 'place',
        size: 9,
        toPlay: 2,
        setup: [
          '.........',
          '.........',
          '......B..',
          '.........',
          '.........',
          '.........',
          '.........',
          '.........',
          '.........',
        ],
        solutions: [{ x: 6, y: 3 }, { x: 5, y: 2 }, { x: 7, y: 2 }, { x: 6, y: 1 }],
        hint: { ko: '흑 화점 옆·아래의 3·4 거리 접근.', en: 'Approach next to the hoshi (knight/one-space).' },
        note: { ko: '실전 변화는 많지만, “귀의 흑에 가까이”가 첫 원칙입니다.', en: 'Many joseki exist; approaching the corner stone is the idea.' },
      },
      {
        id: 'f1-second-corner',
        title: { ko: '맞은편 귀', en: 'Opposite corner' },
        goalLabel: { ko: '목표: 흑이 대각 귀에 두기', en: 'Goal: Black takes the diagonal corner' },
        goal: 'place',
        size: 9,
        toPlay: 1,
        setup: [
          '.........',
          '.........',
          '..B......',
          '.........',
          '.........',
          '.........',
          '.........',
          '.........',
          '.........',
        ],
        solutions: [{ x: 6, y: 6 }],
        hint: { ko: '이미 둔 귀의 대각선 화점.', en: 'The diagonally opposite star.' },
      },
    ],
  },
  {
    id: 'fuseki-2',
    track: 'fuseki',
    order: 2,
    title: { ko: '2. 변으로 뻗기', en: '2. Extending to the side' },
    blurb: {
      ko: '귀를 차지한 뒤 변으로 뻗어 집을 키웁니다. 너무 넓으면 침입 공간이 생깁니다.',
      en: 'After corners, extend along the side. Too wide invites invasion.',
    },
    refs: {
      ko: '참고: In the Beginning — 변의 벌림',
      en: 'Ref: In the Beginning — side extensions',
    },
    problems: [
      {
        id: 'f2-extend',
        title: { ko: '한 칸 벌림', en: 'One-point jump' },
        goalLabel: { ko: '목표: 흑을 변으로 한 칸 벌림', en: 'Goal: one-space extension along the side' },
        goal: 'place',
        size: 9,
        toPlay: 1,
        setup: [
          '.........',
          '.........',
          '..B......',
          '.........',
          '.........',
          '.........',
          '.........',
          '.........',
          '.........',
        ],
        solutions: [{ x: 4, y: 2 }, { x: 2, y: 4 }],
        hint: { ko: '같은 줄에서 한 칸 띄운 자리.', en: 'Jump one point along the same line.' },
      },
      {
        id: 'f2-pincer-feel',
        title: { ko: '협공 감각', en: 'Pincer feel' },
        goalLabel: { ko: '목표: 백 걸침을 협공하는 수', en: 'Goal: pincer the approaching White' },
        goal: 'place',
        size: 9,
        toPlay: 1,
        setup: [
          '.........',
          '.........',
          '..B.W....',
          '.........',
          '.........',
          '.........',
          '.........',
          '.........',
          '.........',
        ],
        solutions: [{ x: 6, y: 2 }, { x: 5, y: 3 }, { x: 5, y: 1 }],
        hint: { ko: '백을 흑과 반대쪽에서 압박.', en: 'Pressure White from the far side of Black.' },
      },
      {
        id: 'f2-avoid-center-early',
        title: { ko: '이른 중앙은 비효율', en: 'Avoid early center' },
        goalLabel: { ko: '목표: 아직 비어 있는 귀 화점', en: 'Goal: take an empty corner star' },
        goal: 'place',
        size: 9,
        toPlay: 1,
        setup: [
          '.........',
          '.........',
          '..B......',
          '.........',
          '....W....',
          '.........',
          '......B..',
          '.........',
          '.........',
        ],
        solutions: [{ x: 6, y: 2 }, { x: 2, y: 6 }],
        hint: { ko: '중앙보다 남은 귀를 우선.', en: 'Prefer remaining corners over the center.' },
      },
    ],
  },
  {
    id: 'fuseki-3',
    track: 'fuseki',
    order: 3,
    title: { ko: '3. 기본 포석 틀', en: '3. Basic opening frames' },
    blurb: {
      ko: '소목(3-4)·화점(4-4)을 섞어 “틀”을 만듭니다. 반복해서 손이 익게 하세요.',
      en: 'Mix 3-4 and 4-4 to build a frame. Drill until the shapes feel natural.',
    },
    refs: {
      ko: '참고: In the Beginning · 입문 포석 틀',
      en: 'Ref: In the Beginning · beginner frameworks',
    },
    problems: [
      {
        id: 'f3-44',
        title: { ko: '4-4 화점', en: 'Play 4-4' },
        goalLabel: { ko: '목표: 좌하귀 4-4', en: 'Goal: 4-4 in bottom-left' },
        goal: 'place',
        size: 9,
        toPlay: 1,
        setup: e9,
        solutions: [{ x: 2, y: 6 }],
        hint: { ko: '왼쪽 아래 화점.', en: 'Bottom-left hoshi.' },
      },
      {
        id: 'f3-34-pair',
        title: { ko: '3-4로 실리', en: '3-4 for territory' },
        goalLabel: { ko: '목표: 우상귀 3-4 (두 방향 중 하나)', en: 'Goal: 3-4 top-right' },
        goal: 'place',
        size: 9,
        toPlay: 1,
        setup: e9,
        solutions: [{ x: 5, y: 2 }, { x: 6, y: 3 }],
        hint: { ko: '귀에서 한 줄 안쪽.', en: 'One line in from the edge of that corner.' },
      },
      {
        id: 'f3-shimari-feel',
        title: { ko: '굳힘 감각', en: 'Enclosure feel' },
        goalLabel: { ko: '목표: 흑 3-4를 굳히는 수', en: 'Goal: enclose the 3-4 stone' },
        goal: 'place',
        size: 9,
        toPlay: 1,
        setup: [
          '.........',
          '.........',
          '.....B...',
          '.........',
          '.........',
          '.........',
          '.........',
          '.........',
          '.........',
        ],
        solutions: [{ x: 6, y: 2 }, { x: 5, y: 3 }, { x: 7, y: 3 }],
        hint: { ko: '같은 귀 안에서 집을 닫는 방향.', en: 'Close the corner around that stone.' },
      },
    ],
  },

  // ─── 사활 ─────────────────────────────────────────────
  {
    id: 'tsumego-1',
    track: 'tsumego',
    order: 1,
    title: { ko: '1. 눈과 급소', en: '1. Eyes & vital points' },
    blurb: {
      ko: '두 눈이 있으면 삽니다. 한 눈·가짜 눈은 위험합니다. 급소를 두는 연습부터.',
      en: 'Two eyes live. One eye or false eyes die. Train the vital point.',
    },
    refs: {
      ko: '참고: Elementary Go Series — Life and Death (Davies)',
      en: 'Ref: Elementary Go Series — Life and Death',
    },
    problems: [
      {
        id: 't1-kill-one-eye',
        title: { ko: '한 눈 찌기', en: 'Kill one-eye' },
        goalLabel: { ko: '목표: 백을 잡는 급소', en: 'Goal: vital point to kill White' },
        goal: 'kill',
        size: 9,
        toPlay: 1,
        setup: [
          '.........',
          '.........',
          '..BBB....',
          '..BWB....',
          '..B.B....',
          '..BBB....',
          '.........',
          '.........',
          '.........',
        ],
        solutions: [{ x: 3, y: 4 }],
        hint: { ko: '백의 눈 자리(빈 칸)를 메우세요.', en: 'Fill White’s eye space.' },
      },
      {
        id: 't1-live-second-eye',
        title: { ko: '두 번째 눈', en: 'Make the second eye' },
        goalLabel: { ko: '목표: 흑이 두 눈을 만드는 수', en: 'Goal: Black’s second-eye move' },
        goal: 'live',
        size: 9,
        toPlay: 1,
        setup: [
          '.........',
          '.WWWWWW..',
          '.WBBBBW..',
          '.WB...W..',
          '.WBBBBW..',
          '.WWWWWW..',
          '.........',
          '.........',
          '.........',
        ],
        solutions: [{ x: 4, y: 3 }],
        hint: { ko: '세 빈 칸의 가운데 — 두면 눈이 둘로 갈라집니다.', en: 'The middle empty point splits the space into two eyes.' },
        note: {
          ko: '양옆 빈 칸이 각각 한 눈이 됩니다. 한쪽만 두면 한 눈만 남을 수 있습니다.',
          en: 'Left and right empties become separate eyes. Side plays can leave only one eye.',
        },
      },
      {
        id: 't1-false-eye',
        title: { ko: '가짜 눈 간파', en: 'Spot the false eye' },
        goalLabel: { ko: '목표: 백 가짜 눈을 깨는 수', en: 'Goal: break White’s false eye' },
        goal: 'kill',
        size: 9,
        toPlay: 1,
        setup: [
          '.........',
          '.........',
          '..BBB....',
          '..B.B....',
          '..BWBB...',
          '...WW....',
          '.........',
          '.........',
          '.........',
        ],
        solutions: [{ x: 3, y: 3 }],
        hint: { ko: '대각이 약해 보이는 빈 칸.', en: 'The diagonal weakness in the “eye”.' },
      },
    ],
  },
  {
    id: 'tsumego-2',
    track: 'tsumego',
    order: 2,
    title: { ko: '2. 기본 사·활 수', en: '2. Basic kill/live moves' },
    blurb: {
      ko: '끼움·젖힘·치중은 사활의 기본 수법입니다. 한 수씩 정확히.',
      en: 'Placement, hane, and throw-in ideas appear constantly in life-and-death.',
    },
    refs: {
      ko: '참고: Life and Death · Graded Go Problems Vol.2',
      en: 'Ref: Life and Death · Graded Go Problems Vol.2',
    },
    problems: [
      {
        id: 't2-placement',
        title: { ko: '치중(급소 꽂기)', en: 'Placement' },
        goalLabel: { ko: '목표: 눈 모양을 깨는 치중', en: 'Goal: nakade placement that kills the eye' },
        goal: 'kill',
        size: 9,
        toPlay: 1,
        setup: [
          '.........',
          '.........',
          '.BBBBB...',
          '.B...B...',
          '.B...B...',
          '.B...B...',
          '.BBBBB...',
          '.........',
          '.........',
        ],
        solutions: [{ x: 3, y: 4 }],
        hint: { ko: '큰 눈 한가운데 — 두면 두 눈이 되지 않습니다.', en: 'Center of the big eye — White cannot make two eyes.' },
        note: {
          ko: '3×3 눈 공간의 중앙 치중이 기본 급소입니다(《Life and Death》 전통).',
          en: 'Center of a 3×3 eye space is the classic nakade (Life and Death tradition).',
        },
      },
      {
        id: 't2-capture-race-lite',
        title: { ko: '수상전 맛보기', en: 'Capture-race lite' },
        goalLabel: { ko: '목표: 먼저 따내는 수', en: 'Goal: capture first' },
        goal: 'capture',
        size: 9,
        toPlay: 1,
        setup: [
          '.........',
          '.........',
          '..BBB....',
          '.BW.WB...',
          '..BBB....',
          '.........',
          '.........',
          '.........',
          '.........',
        ],
        solutions: [{ x: 3, y: 3 }],
        hint: { ko: '가운데를 메우면 백이 잡힙니다.', en: 'Fill the middle liberty.' },
      },
      {
        id: 't2-self-atari-avoid',
        title: { ko: '자살수 피하기', en: 'Avoid self-atari' },
        goalLabel: { ko: '목표: 흑이 안전하게 잡는 수', en: 'Goal: safe capturing move' },
        goal: 'capture',
        size: 9,
        toPlay: 1,
        setup: [
          '.........',
          '.........',
          '...BBB...',
          '..BW.B...',
          '...BBB...',
          '.........',
          '.........',
          '.........',
          '.........',
        ],
        solutions: [{ x: 4, y: 3 }],
        hint: { ko: '백의 열린 활로를 막으세요.', en: 'Close White’s open liberty.' },
      },
    ],
  },
  {
    id: 'tsumego-3',
    track: 'tsumego',
    order: 3,
    title: { ko: '3. 반복 훈련', en: '3. Drill set' },
    blurb: {
      ko: '같은 패턴을 반복해야 실전에서 보입니다. 틀려도 다시 두세요.',
      en: 'Repetition makes shapes recognizable over the board.',
    },
    refs: {
      ko: '참고: Graded Go Problems — 반복 드릴 철학',
      en: 'Ref: Graded Go Problems — drill philosophy',
    },
    problems: [
      {
        id: 't3-net',
        title: { ko: '그물 맛보기', en: 'Net feel' },
        goalLabel: { ko: '목표: 백 탈출을 막는 수', en: 'Goal: stop White escaping' },
        goal: 'place',
        size: 9,
        toPlay: 1,
        setup: [
          '.........',
          '.........',
          '..B.B....',
          '..BWB....',
          '...B.....',
          '.........',
          '.........',
          '.........',
          '.........',
        ],
        solutions: [{ x: 3, y: 2 }],
        hint: { ko: '백 위쪽 도망길을 막으세요.', en: 'Block the escape upward.' },
      },
      {
        id: 't3-snap',
        title: { ko: '축·몰아넣기 감각', en: 'Drive & squeeze' },
        goalLabel: { ko: '목표: 백을 몰아 따내는 수', en: 'Goal: squeeze-capture' },
        goal: 'capture',
        size: 9,
        toPlay: 1,
        setup: [
          '.........',
          '.........',
          '.BBB.....',
          '.BWB.....',
          '.B.B.....',
          '..B......',
          '.........',
          '.........',
          '.........',
        ],
        solutions: [{ x: 2, y: 4 }],
        hint: { ko: '백 아래 활로.', en: 'Liberty under White.' },
      },
      {
        id: 't3-review-vital',
        title: { ko: '급소 복습', en: 'Vital-point review' },
        goalLabel: { ko: '목표: 백을 죽이는 급소', en: 'Goal: killing vital point' },
        goal: 'kill',
        size: 9,
        toPlay: 1,
        setup: [
          '.........',
          '.BBBBB...',
          '.B.W.B...',
          '.B...B...',
          '.BBBBB...',
          '.........',
          '.........',
          '.........',
          '.........',
        ],
        solutions: [{ x: 3, y: 3 }],
        hint: { ko: '백 아래 공배 중심.', en: 'The empty point under White.' },
      },
    ],
  },
]

export function stagesForTrack(track: import('./types').TrackId): LearnStage[] {
  return STAGES.filter((s) => s.track === track).sort((a, b) => a.order - b.order)
}

export function findStage(stageId: string): LearnStage | undefined {
  return STAGES.find((s) => s.id === stageId)
}
